---
abstract: 'OX::RouteBuilder which routes to an action method in a controller class based on HTTP verbs'
author:
  - 'Thomas Klausner <domm@cpan.org>'
  - 'Validad GmbH http://validad.com'
build_requires:
  Module::Build: 0.3601
  OX: 0
  Plack::Test: 0
  Test::More: 0
  Test::Path::Router: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OX-RouteBuilder-REST
requires:
  Moose: 0
  OX::RouteBuilder: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/domm/OX-RouteBuilder-REST.git
version: 0.003
